"""add initial schema

Revision ID: 2267183964a7
Revises:
Create Date: 2026-07-03 12:34:22.474265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2267183964a7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kg_category",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "FUND",
                "TECH",
                "MANPOWER",
                "EXPORT",
                "SALES",
                "STARTUP",
                "MANAGEMENT",
                "COMMERCIALIZATION",
                "INCUBATION",
                "EDUCATION",
                "EVENT",
                name="category_name",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_source",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=True),
        sa.Column("collect_type", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("org_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("kakao_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="ACTIVE", nullable=False
        ),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category_mapping",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("raw_category", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["kg_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_profile",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("business_type", sa.String(length=50), nullable=True),
        sa.Column("company_stage", sa.String(length=50), nullable=True),
        sa.Column("region_code", sa.String(length=20), nullable=True),
        sa.Column("region_name", sa.String(length=100), nullable=True),
        sa.Column("industry_code", sa.String(length=20), nullable=True),
        sa.Column("founded_date", sa.Date(), nullable=True),
        sa.Column("business_years", sa.Integer(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("annual_revenue", sa.BigInteger(), nullable=True),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("spec_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("notice_group_key", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("target_business_years_max", sa.Integer(), nullable=True),
        sa.Column("application_start_date", sa.Date(), nullable=True),
        sa.Column("application_end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("is_actionable", sa.Boolean(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("apply_url", sa.String(length=500), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["notice_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bizinfo_raw",
        sa.Column("Key", sa.String(length=255), nullable=False),
        sa.Column("Field", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("Key"),
    )
    op.create_table(
        "business_plan",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("company_profile_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("file_type", sa.String(length=20), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("analysis_json", sa.JSON(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kstartup_raw",
        sa.Column("Key", sa.String(length=255), nullable=False),
        sa.Column("Field", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("Key"),
    )
    op.create_table(
        "notice_attachment",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("file_type", sa.String(length=20), nullable=True),
        sa.Column("parsed_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_category_map",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("mapping_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["category_mapping.id"],
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_chunk",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=30), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_region",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("region_code", sa.String(length=20), nullable=False),
        sa.Column("region_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notice_target_type",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refined_column",
        sa.Column("Key", sa.String(length=255), nullable=False),
        sa.Column("Field", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["notice.id"],
        ),
        sa.PrimaryKeyConstraint("Key"),
    )
    op.create_table(
        "business_plan_chunk",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("business_plan_id", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=30), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["business_plan_id"],
            ["business_plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_log",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_profile_id", sa.Integer(), nullable=False),
        sa.Column("business_plan_id", sa.Integer(), nullable=True),
        sa.Column("run_status", sa.String(length=20), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=True),
        sa.Column("query_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_plan_id"],
            ["business_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_report",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("match_run_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["match_run_id"],
            ["match_log.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_result",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("recommendation_run_id", sa.Integer(), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("eligibility_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("item_fit_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "business_fit_score", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("growth_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("bonus_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("eligibility_status", sa.String(length=20), nullable=True),
        sa.Column("recommendation_level", sa.String(length=20), nullable=True),
        sa.Column("summary_reason", sa.Text(), nullable=True),
        sa.Column("weakness", sa.Text(), nullable=True),
        sa.Column("strategy_suggestion", sa.Text(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["notice_id"],
            ["notice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_run_id"],
            ["match_log.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_result")
    op.drop_table("match_report")
    op.drop_table("match_log")
    op.drop_table("business_plan_chunk")
    op.drop_table("refined_column")
    op.drop_table("notice_target_type")
    op.drop_table("notice_region")
    op.drop_table("notice_chunk")
    op.drop_table("notice_category_map")
    op.drop_table("notice_attachment")
    op.drop_table("kstartup_raw")
    op.drop_table("business_plan")
    op.drop_table("bizinfo_raw")
    op.drop_table("notice")
    op.drop_table("company_profile")
    op.drop_table("category_mapping")
    op.drop_table("user")
    op.drop_table("organization")
    op.drop_table("notice_source")
    op.drop_table("kg_category")
    # ### end Alembic commands ###
