"""secondary_filtering_judgment 테이블 추가

Revision ID: 4308fcbd06d3
Revises: 6742607b62d0
Create Date: 2026-07-16 11:50:53.157634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4308fcbd06d3"
down_revision: Union[str, Sequence[str], None] = "6742607b62d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secondary_filtering_judgment",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("business_plan_id", sa.Integer(), nullable=False),
        sa.Column("notice_id", sa.Integer(), nullable=False),
        sa.Column("profile_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("judgments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "judged_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["business_plan_id"], ["business_plan.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["notice_id"], ["notice.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_plan_id",
            "notice_id",
            "profile_fingerprint",
            name="uq_secondary_filtering_judgment_key",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secondary_filtering_judgment")
    # ### end Alembic commands ###
