"""match_log에 secondary_filtering_log 컬럼 추가

Revision ID: 681ee3c17bf0
Revises: c5260495294c
Create Date: 2026-07-14 04:09:55.876915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "681ee3c17bf0"
down_revision: Union[str, Sequence[str], None] = "c5260495294c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_log",
        sa.Column(
            "secondary_filtering_log",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_log", "secondary_filtering_log")
    # ### end Alembic commands ###
