"""add notice organization fk

Revision ID: ce3fa2a501bc
Revises: 4058f8260dc6
Create Date: 2026-07-03 12:46:18.299249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3fa2a501bc'
down_revision: Union[str, Sequence[str], None] = '4058f8260dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notice', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notice', type_='foreignkey')
    op.drop_column('notice', 'organization_id')
    # ### end Alembic commands ###
